// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANi0Ralh54JMFlFwWRcbPKLM2T5NelV2I',
    appId: '1:993255249361:web:ac0be4125d9bf3c023bcf0',
    messagingSenderId: '993255249361',
    projectId: 'shoppingapp-7fa59',
    authDomain: 'shoppingapp-7fa59.firebaseapp.com',
    storageBucket: 'shoppingapp-7fa59.appspot.com',
    measurementId: 'G-C8X5G2EG07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7O2H4bWxOrFKfDR1vKuYFVG_IOiE3O08',
    appId: '1:993255249361:android:6e057c8a273e189223bcf0',
    messagingSenderId: '993255249361',
    projectId: 'shoppingapp-7fa59',
    storageBucket: 'shoppingapp-7fa59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfqqTFYaltXU8F6-VtJQgeugGUrlJJ7nM',
    appId: '1:993255249361:ios:37422b771844651623bcf0',
    messagingSenderId: '993255249361',
    projectId: 'shoppingapp-7fa59',
    storageBucket: 'shoppingapp-7fa59.appspot.com',
    iosClientId: '993255249361-aatqejn1c95u49j21vdp8rpdcgj1mt12.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfqqTFYaltXU8F6-VtJQgeugGUrlJJ7nM',
    appId: '1:993255249361:ios:37422b771844651623bcf0',
    messagingSenderId: '993255249361',
    projectId: 'shoppingapp-7fa59',
    storageBucket: 'shoppingapp-7fa59.appspot.com',
    iosClientId: '993255249361-aatqejn1c95u49j21vdp8rpdcgj1mt12.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );
}
